name: Upload image on release

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - run: sudo apt-get update
    - run: sudo apt-get install -y kpartx qemu qemu-user-static binfmt-support parted
    
    - run: wget --progress=dot:giga https://downloads.openwrt.org/releases/18.06.4/targets/brcm2708/bcm2710/openwrt-18.06.4-brcm2708-bcm2710-rpi-3-ext4-factory.img.gz
    - run: gzip -d openwrt-18.06.4-brcm2708-bcm2710-rpi-3-ext4-factory.img.gz
    - run: sudo pimod/pimod.sh RaspberryPi-OpenWRT.Pifile
    - run: zip RaspberryPi-OpenWRT.zip RaspberryPi-OpenWRT.img
    
    - uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
