name: Test image building on push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y kpartx qemu qemu-user-static binfmt-support parted
    
    - name: Download openwrt-18.06.4-brcm2708-bcm2710-rpi-3-ext4-factory.img
      run: |
        wget --progress=dot:giga https://downloads.openwrt.org/releases/18.06.4/targets/brcm2708/bcm2710/openwrt-18.06.4-brcm2708-bcm2710-rpi-3-ext4-factory.img.gz
        gzip -d openwrt-18.06.4-brcm2708-bcm2710-rpi-3-ext4-factory.img.gz
    - name: Run RaspberryPi-OpenWRT.Pifile
      run: sudo pimod/pimod.sh RaspberryPi-OpenWRT.Pifile
