name: Test Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y kpartx qemu qemu-user-static binfmt-support parted
    - name: Run pimod.sh tests/RaspberryPi/OpenWRT.Pifile
      run: sudo pimod/pimod.sh tests/RaspberryPi/OpenWRT.Pifile
